version: '1'
services:

  db:
    image: mongo:4.0.8
    command: mongod --quiet --logpath /dev/null
    restart: unless-stopped
    networks:
      - repo_processor
    environment:
      MONGODB_LOG_DIR: /dev/null
    ports:
      - 27017:27017
    volumes:
      - ./data/:/data/db

  processor:
    build: ./python
    container_name: processor
    user: root
    volumes:
      - ./python:/python
      - ./data:/data/db
    entrypoint: python3 -u python/main.py
    ports:
      - '8501:8501'
    networks:
      - repo_processor
    environment:
      DB_URL: mongodb://db
      DB_NAME: repo_db
      DB_COLLECTION: repos
      DB_DATA_DIR: /data/db
      SPARK_RESULT_DIR: /result
      SPARK_PRETTY_OUT_DIR: /pretty_csv	
      PYTHONUNBUFFERED: 1

volumes:
  db:
  processor:

networks:
  repo_processor:
    driver: bridge